name: fastq2table
description: Convert fastq input into TSV output
keywords:
    - fastq

tools:
  - linux shell commands

input:
  - meta:
      type: map
      description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]

output:
  - meta:
      type: map
      description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
    - "@agalitsyna"
