name: simple_encode
description: Encode input DNA in binary code
keywords:
    - encode
    - bin
    - hashing

tools:
  - simple_encode_fasta2bin:
      description: Simple fasta2bin C code that encodes each input DNA nucleotide as a 2-bit code.
      licence: ['MIT']
  - simple_encode_fastq2bin:
      description: Simple fastq2bin C code that encodes each input DNA nucleotide as a 2-bit code.
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.

output:
  - meta:
      type: map
      description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false, mode: 'fasta|fastq']
  - bin:
      type: file
      description: File containing encoded sequences
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
    - "@agalitsyna"
